### ISSUE TITLE
Skill deployment question

### ISSUE THREAD

**Issue by ymeloch** [drunnells/alexa-mint-skill#1]
Dustin,

Thank you so much for the Mint skill page! It’s super great!

I’ve a question regarding the procedure.

I followed the entire procedure and successfully applied all steps.

- Mint api is working well (I can see my account info)
- RHEL 7.2 webserver is up and running
- HTTPS (w/ SSL certificate) is working
- config.php was successfully modified 
- Can https the following link: https://[websiteURL].com/alexa-mint-skill/alexa.php (getting the following output: [] -> is that expected?)

When I’m trying to test the new skill (step #24), I’m not seeing any JSON error but I’m getting the following output:

**Service Request:**
```
{
  "session": {
    "sessionId": "SessionId.ca74e596-e740-4af7-952b-26375d19c956",
    "application": {
      "applicationId": "amzn1.ask.skill.47ce287c-8df2-4cc6-bb0b-cfda4b438b3a"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHVLTG66IMV677YSN2RGYR6U4LGBXPZZAHKBWQDRCJMHMCFELQMVQJTIZVV4B47R3QJVJLV6E5GI3MY5LEEGX2ZJNYKU53PJXGL2K4OPOFYPY55QM4C6O5ITVROKZMJA2RBGNTDPBWWHGXOU6DAUL7SQHBIPBA36AYT4N2ZQSZ5BWSRS7AGKMWAV5ILGAF267NNFDZJUT2CMBOI"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.c8e377c4-2bd2-4b8a-bd1a-8957a2f68137",
    "locale": "en-US",
    "timestamp": "2017-04-14T04:17:59Z",
    "intent": {
      "name": "Mint",
      "slots": {
        "budgetType": {
          "name": "budgetType"
        },
        "actionType": {
          "name": "actionType"
        },
        "bankType": {
          "name": "bankType",
          "value": "bank"
        }
      }
    }
  },
  "version": "1.0"
}
```

**Service Response**
```
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "**Mint was unable to process your request.**"
    },
    "card": {
      "content": "**Mint was unable to process your request**.",
      "title": "Mint",
      "type": "Simple"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {
    "countActionList": {
      "read": "true",
      "category": "true",
      "curentTask": "none"
    }
  }
}
```

Also, when asking Alexa the following questions, Alexa is unable to answer
•	Alexa, ask Mint for my bank balance.
•	Alexa, ask Mint for my balances.
•	Alexa, ask Mint for my credit card balance.

What am I missing?

Thanks much in advance!

**Comment by drunnells** [comment]
Thanks for trying this skill!

It looks like the Service Request JSON is good. The alexa.php is supposed to see the bankType value as "bank" and run the getMintDetail() function. From there getMintDetail() should just run mintapi on the command line and get some results to parse. I suspect that this is where it is failing - mintapi is not returning JSON to parse. We should be able to test this with a test script, try creating a test.php file with the contents below in the same dir with alexa.php:

```
<?php
require_once('config.php');
require_once('mintLib.php');
$mintDetail = getMintDetail($configArray);
print_r($mintDetail);
?>
```

If you don't see the balances and other details from your mint account, we'll know that the problem is something to do with how we are running mintapi. The command line being executed is in mintLIb.php on line 15. With it fully populated it probably looks something like:

`/opt/python-2.7.2/bin/mintapi --session ABCDABCDABCD --thx_guid 123412341234 mintuser@example.com mypassword`

try replacing the maintapi path, session, thx_guid, username and password in the above with your own and make sure you get an answer from mintapi. That should help narrow down where any problem might be. 

One thing to note is that mintapi says that it will work with chromeapi to obtain the ius_session and thx_guid automatically, however I wasn't able to get that to work in my environment and it is not implemented in the alexa-mint-skill yet. If you were able to get mintapi to work without manually obtaining the ius_session and thx_guid, that might be what is failing here.

**Comment by ymeloch** [comment]
Issue resolved. 
1. had to change the "mintAPI" path (line 19 in config.php file)
2. I created the skill using a different amazon account than the one attached to Alexa (hence it was missing from the Skills list).

Special thanks to Dustin for his help!
